name: Deploy (Batch)

on:
  push:
    branches: [ "dev" ] # 일단 개발용으로 구축

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  ECR_REPO: ${{ secrets.ECR_REPO_BATCH }}
  IMAGE_TAG: ${{ github.sha }}
  EC2_INSTANCE_ID_BATCH: ${{ secrets.EC2_INSTANCE_ID_BATCH }}
  CONTAINER_NAME: oot-batch
  SPRING_PROFILE: batch
  DEPLOY_TARGET: batch
  APP_PORT: "8081" # 배치 서버는 포트 매핑이 필요 없으면 제거 가능

jobs:
  deploy-batch:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-batch
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/github-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Build & Push to ECR
        id: push
        run: ./scripts/ecr-push.sh

      - name: Deploy to EC2 (Batch)
        env:
          FULL_URI: ${{ steps.push.outputs.FULL_URI }}
        run: ./scripts/deploy.sh